version: "3.8"

services:

  postgres:
    container_name: client-api-pg
    image: postgres:13.4
    restart: always
    deploy:
      resources:
        limits:
          memory: 700M
    environment:
      POSTGRES_PASSWORD: "Iz10mtRj59"
    ports:
      - "12218:5432"
    command:
      - "docker-entrypoint.sh"
      - "-c"
      - "max-connections=800"